<a href="https://colab.research.google.com/github/MikeSalnikov/MathAn/blob/main/Lin_Alg_lesson2_%D0%94%D0%97.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
from numpy.linalg import norm

__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

необходимо, чтобы число столбцов матрицы **A** было равно числу строк матрицы **B**

*Ответ:* Соответственно a) AB и BA не определены б) AB - размерность 2x3, BA не определена в) AB размерность 8x8, BA размерность 3x3 г) AB и BA размерность 4x4

а) A — матрица 4×2 , B — матрица 4×2 ;

In [6]:
A = np.ones((4,2))
B = np.ones((4,2))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Матрица B
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


ValueError: ignored

б) A — матрица 2×5 , B — матрица 5×3 ;

In [9]:
A = np.ones((2,5))
B = np.ones((5,3))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Матрица B
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матрица AB
[[5. 5. 5.]
 [5. 5. 5.]]


ValueError: ignored

в) A — матрица 8×3 , B — матрица 3×8 ;

In [8]:
A = np.ones((8,3))
B = np.ones((3,8))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Матрица B
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
Матрица AB
[[3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3. 3. 3. 3.]]
Матрица BA
[[8. 8. 8.]
 [8. 8. 8.]
 [8. 8. 8.]]


г) A — квадратная матрица 4×4 , B — квадратная матрица 4×4 .

In [10]:
A = np.ones((4,4))
B = np.ones((4,4))
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица AB\n{np.dot(A, B)}')
print(f'Матрица BA\n{np.dot(B, A)}')

Матрица A
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Матрица B
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Матрица AB
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]
Матрица BA
[[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

A+B=

$$\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix} + \begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix} = \begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix} .$$

= \begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}

AxB = 


$$\begin{pmatrix}
a_{11} & a_{12}\\ 
a_{21} & a_{22}
\end{pmatrix} \begin{pmatrix}
b_{11} & b_{12}\\ 
b_{21} & b_{22}
\end{pmatrix}=\begin{pmatrix}
(a_{11}b_{11} + a_{12}b_{21}) & (a_{11}b_{12} + a_{12}b_{22})\\ 
(a_{21}b_{11} + a_{22}b_{21}) & (a_{21}b_{12} + a_{22}b_{22})
\end{pmatrix}.$$

\begin{pmatrix} 14+0-2 & 1-1+-25\ 34+00 & 3-1+0*5 \end{pmatrix}=

итог = \begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}

In [11]:
A = np.array([[1,-2],[3,0]])
B = np.array([[4,-1],[0,5]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица A+B\n{A+B}')
print(f'Матрица AxB\n{np.dot(A, B)}')

Матрица A
[[ 1 -2]
 [ 3  0]]
Матрица B
[[ 4 -1]
 [ 0  5]]
Матрица A+B
[[ 5 -3]
 [ 3  5]]
Матрица AxB
[[  4 -11]
 [ 12  -3]]


*рисование формул занимает слишком много времени, суть понятна) прошу понять и принять без ручных расчетов*

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

In [12]:
A = np.array([[1,7],[3,-6]])
B = np.array([[0,5],[2,-1]])
C = np.array([[2,-4],[1,1]])
print(f'Матрица A\n{A}')
print(f'Матрица B\n{B}')
print(f'Матрица C\n{B}')
print(f'Матрица 3A-2B+4C\n{3*A+(-2)*B+4*C}')

Матрица A
[[ 1  7]
 [ 3 -6]]
Матрица B
[[ 0  5]
 [ 2 -1]]
Матрица C
[[ 0  5]
 [ 2 -1]]
Матрица 3A-2B+4C
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.

In [13]:
A = np.array([[4,1],[5,-2],[2,3]])
print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')
print(f'матрица A*AT:\n{np.dot(A,A.T)}')
print(f'матрица AT*A:\n{np.dot(A.T,A)}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]
матрица A*AT:
[[17 18 11]
 [18 29  4]
 [11  4 13]]
матрица AT*A:
[[45  0]
 [ 0 14]]


5*. Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

In [14]:
import random
 
def matrixmult(m1,m2):
    s=0     #сумма
    t=[]    #временная матрица
    m3=[] # конечная матрица
    if len(m2)!=len(m1[0]):
        print("Матрицы не могут быть перемножены")        
    else:
        r1=len(m1) #количество строк в первой матрице
        c1=len(m1[0]) #Количество столбцов в 1   
        r2=c1           #и строк во 2ой матрице
        c2=len(m2[0])  # количество столбцов во 2ой матрице
        for z in range(0,r1):
            for j in range(0,c2):
                for i in range(0,c1):
                   s=s+m1[z][i]*m2[i][j]
                t.append(s)
                s=0
            m3.append(t)
            t=[]           
    return m3
 
def creatematrix(r,c):
    t=[]
    m=[]
    for i in range(0,r):
        for j in range(0,c):
            t.append(random.randint(1,10))
        m.append(t)
        t=[]
    return m
 
c1=1
r2=2
while c1!=r2:
    print("Кол-во столбцов в 1 матрице должно быть = кол-ву строк 2 матрицы")
    r1=int(input('Введите кол-во строк для 1 матрицы >'))
    c1=int(input('Введите кол-во столбцов для 1 матрицы>'))
    r2=int(input('Введите кол-во строк для второй матрицы >'))
    c2=int(input('Введите кол-во столбцов для 2 матрицы >'))
    
 
m1=creatematrix(r1,c1)
m2=creatematrix(r2,c2)
    
 
print("1я матрица ",m1)
print('2я матрица ',m2)
 
m3=matrixmult(m1,m2)
print("произведение матриц",m3)

Кол-во столбцов в 1 матрице должно быть = кол-ву строк 2 матрицы
Введите кол-во строк для 1 матрицы >2
Введите кол-во столбцов для 1 матрицы>3
Введите кол-во строк для второй матрицы >3
Введите кол-во столбцов для 2 матрицы >2
1я матрица  [[4, 8, 1], [2, 1, 2]]
2я матрица  [[3, 5], [6, 2], [1, 9]]
произведение матриц [[61, 45], [14, 30]]
